# Generated by Django 2.0.7 on 2018-07-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20180729_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='intraday_alert',
            field=models.BooleanField(default=False, help_text='Set if you want to check intraday prices'),
        ),
    ]
