version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.6.1
        environment:
          DATABASE_URL: postgres:///stock_price_alert
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: stock_price_alert
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/test.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            py.test --cov=./
            codecov --token=token
      - store_artifacts:
          path: test-reports/
          destination: test-reports/
